#!/bin/bash
echo 'running apt-get install'

sudo apt-get install --fix-missing -y \
alien \
build-essential \
cmake \
ethtool \
gfortran \
git \
gstreamer1.0-alsa \
gstreamer1.0-plugins-bad \
gstreamer1.0-plugins-base \
gstreamer1.0-plugins-good \
gstreamer1.0-plugins-ugly \
gtk-3.0 \
iw \
libappindicator1 \
libatlas-base-dev \
libavcodec-dev \
libavformat-dev \
libav-tools \
libcanberra-gtk-module \
libgl1-mesa-dev \
libgles2-mesa-dev \
libgstreamer1.0-dev \
libgstreamer-plugins-base1.0-dev \
libgtk2.0-dev \
libindicator7 \
libjasper-dev \
libjpeg62-turbo-dev \
libmtdev-dev \
libmysqlclient-dev \
libnl-3-dev \
libnl-genl-3-dev \
libpng12-dev \
libportmidi-dev \
libsdl1.2-dev \
libsdl2-2.0-0 \
libsdl2-dev \
libsdl2-gfx-1.0.0 \
libsdl2-gfx-dev \
libsdl2-image-2.0-0 \
libsdl2-image-dev \
libsdl2-mixer-2.0-0 \
libsdl2-mixer-dev \
libsdl2-net-2.0-0 \
libsdl2-net-dev \
libsdl2-ttf-2.0-0 \
libsdl2-ttf-dev \
libsdl-image1.2-dev \
libsdl-mixer1.2-dev \
libsmpeg-dev \
libssl-dev \
libswscale-dev \
libtiff5-dev \
libv4l-dev \
libxss1 \
mercurial \
pkg-config \
python3-cairocffi \
python3-dev \
python3-pil \
python3-pip \
python3-serial \
python3-tk \
python-cairocffi \
python-configparser \
python-dev \
python-enchant \
python-gst0.10 \
python-gst0.10-dev \
python-matplotlib \
python-mysqldb \
python-numpy \
python-opengl \
python-pil \
python-pygame \
python-scikits-learn \
python-scipy \
python-scitools \
python-serial \
python-setuptools \
python-skimage \
python-skimage-lib \
python-sklearn \
python-sklearn-lib \
rfkill \
rpm \
subversion \
xclip \
zlib1g-dev
